version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/people_db
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
